### ISSUE TITLE
Sequential schemes don't seem to work for heatmaps with numerical values

### ISSUE THREAD

**Issue by fxwiegand** [datavzrd/datavzrd#318]
Configs like the following don't seem to work at the moment:
```yaml
plot:
    heatmap:
        color-scheme: viridis
        scale: linear
```
Using `range` or categorial color-schemes seems to work fine.
