### ISSUE TITLE
More sophisticated mechanism for `desc`

### ISSUE THREAD

**Issue by johanneskoester** [datavzrd/datavzrd#327]
## 1: Change of description definition:

```yaml
view:
  foo:
    desc: as before
    render-table:
      columns:
        x:
          desc: |
            Description of column x, markdown allowed.
```

The descriptions for each column should be automatically rendered as a markdown list below the global description for the view.

## 2: Change of description display

1. The info button on the top right is removed.
2. The description is put into a collapse widget, with a header "Description". The widget is collapsed at the beginning.
