### ISSUE TITLE
Permanent headline and descriptive text above table :feature:

### ISSUE THREAD

**Issue by kilpert** [datavzrd/datavzrd#360]
I suggest having a **permanent** markdown field above the table that can be used for a headline and a few descriptive sentences. This field should **always be visible**. 

The idea is pretty much the same as for the layout of tables in publications, where each table has a headline and a short text explaining what the following table is about. 

There is already `desc` in `views`, which could be used for this as well. However, in its current implementation the intention is probably to use desc for descriptive text that does not need to be visible most of the time (e.g. column descriptions). Desc is fine, but an additional field (above desc) for the headline would be very helpful, especially for people trying to quickly understand whether the current datavzrd page is relevant to them or not. The current click-on implementation of desc is also helpful and should stay. This feature request is about having a permanent field in addition.

**Comment by fxwiegand** [comment]
Since this is hardly related to #327 (at least for the implemetation and spec side) it probably makes sense to come up with a solution that fits all. What are your thoughts @johanneskoester? It might be an option to make the initial state of the description configurable. But then we would need a second collapse for the individual column description mentioned in #327   because those should definitely not be visible. I get the point of having an "always on" description but having a config like this is probably not the cleanest solution:

```yaml
views:
  oscars:
    dataset: oscars
    permanent-desc: |
      ### All winning oscars beginning in the year 1929.
      This table contains *all* winning oscars for best actress and best actor.
    desc:  |
        The Academy Awards, better known as the Oscars, are awards for artistic and technical merit for the American film industry.
        The awards are regarded by many as the most prestigious, significant awards in the entertainment industry in the United States
    page-size: 25

**Comment by kilpert** [comment]
Maybe, we could have multiple descriptions (like a list), which are all displayed one after the other (in order).
```
views:
  bla:
    dataset: bla
    descriptions:
      textbox1:
        visible: on-start
      textbox2:
        visible: on-click
        position: top
      textbox3:
        visible: 
          - on-start
          - collapsable
        position: bottom
```
