### ISSUE TITLE
Improve documentation for type keyword of heatmap definitions

### ISSUE THREAD

**Issue by dlaehnemann** [datavzrd/datavzrd#576]
I think I found a funny corner case, where this test here is not working as intended:
https://github.com/datavzrd/datavzrd/blob/60fdbd05110b7d5b639d3ef5c0831e0b214003c2/src/spec.rs#L163

I have a table  with the following column spec:

```
        log2fdc:
          plot:
            heatmap:
              type: quantitative
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain-mid: 0
```

And it throws the error:
```
Error: Given range for column "log2fdc" of view "gfold_table" with specified domain-mid must be of length 3.
```

Interestingly, if I remove the `type: quantitative` line (which isn't supported by datavzrd, I think), then I don't get the error. So this seems like a case of somewhat erroneous parsing, that throws a "misleading" error.
