### ISSUE TITLE
Allow color definition for tick and bar plots

### ISSUE THREAD

**Issue by fxwiegand** [datavzrd/datavzrd#586]
datavzrd needs to allow the following definitions for tick and bar plots:
```yaml
plot:
  ticks:
    color:
      scale: linear
      range: ...
      domain: ...
      domain-mid: ...
```
