### ISSUE TITLE
No sorting function and problem with filtering function in generated report

### ISSUE THREAD

**Issue by edg1983** [datavzrd/datavzrd#892]
Hello,

Thanks for the great tool!

I'm using datavzrd 2.50.3 to generate a report from a tab-separated table with 97840 rows and 15 columns.

However, the HTML report does not offer an option to sort the columns, a function that is present in your example report.

Moreover, the filter function is only present for text columns. When I try to filter on text columns, I get a table with the list of possible values and their corresponding row. Here, I can input a value of interest and see in which rows it is present, but I can't find a way to actually restrict the displayed rows based on the filter. I can only highlight a specific row. This makes the filter function ineffective and of limited usefulness.

This is completely different from the nice filter functionality I see in your example report.

Are some functionality not available or limited due to the size of the dataset? Or am I doing something wrong?

Thanks a lot!

This is the config file I'm using. 

```yml
name: Colocalization modules
max-in-memory-rows: 20000

datasets:
  coloc_modules:
    path: 2024_12_17_coloc_Master_table_cardinal_Cs_modules.tsv
    separator: "\t"
    
views:
  colocalization:
    dataset: coloc_modules
    desc: |
      Table view for colocalization modules.
    page-size: 50
    render-table:
      columns:
        ENSG:
          link-to-url:
            Ensembl:
              url: https://www.ensembl.org/Homo_sapiens/Gene/Summary?g={value}
              new-window: true
            GTeX:
              url: https://www.gtexportal.org/home/gene/{value}
              new-window: true
            GeneCards:
              url: https://www.genecards.org/cgi-bin/carddisp.pl?gene={value}
              new-window: true
        most_likely_joint_PP:
          precision: 3
          plot:
            heatmap:
              scale: linear
              clamp: true
              range: [0, 1]
              color-scheme: reds
        beta:
          precision: 3
          plot:
            heatmap:
              scale: linear
              clamp: true
              range: [-100, 100]
              color-scheme: purples
      add-columns:
        gnomAD_link:
          value: function my_new_col(row) { return row.most_likely_snp.replace(/:/g, "-") }
          link-to-url:
            gnomAD:
              url:  https://gnomad.broadinstitute.org/variant/{value}?dataset=gnomad_r4
              new-window: true
```
