### ISSUE TITLE
heatmap legends

### ISSUE THREAD

**Issue by johanneskoester** [datavzrd/datavzrd#955]
I suggest to add a feature to show heatmap values in a legend above or below the table. This could be configured as follows:

```
regex("col[1-9]+"):
  plot:
      heatmap:
          scale: ordinal
          color-scheme: category20
          legend:
              title: some title
          aux-domain-columns:
            - regex("col[1-9]+")
  ```
The example assumes there are several similarly named columns which shall yield a joint heatmap.
Note the title field in the heatmap definition. Datavzrd can use this (it is the same for all these columns) to ensure that the legend is only displayed once. The title field should probably be mandatory.
